site_name: Pokémini Go
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  logo: assets/pokeball.png
  favicon: assets/pokeball.png
  features:
    - navigation.sections
    - toc.integrate
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js